server:
  port: 8080

spring:
  datasource:
    environments: development
    primary:
      name: testdb0
      url: jdbc:mysql://127.0.0.1:3306/test0
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test0
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      name: testdb1
      url: jdbc:mysql://127.0.0.1:3306/test1
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.iflytek.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
