server:
  port: 8080



sharding:
  jdbc:
    datasource:
      names: test0,test1
      test0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test0
        username: root
        password: root
      test1:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test1
        username: root
        password: root
    config:
      sharding:
        props:
          sql:
            show: true # 显示sql
          #executor:
            #size: 4 # 工作线程数量，默认是CPU核数
        # 未配置分片规则的表将通过默认的数据源定位
        default-data-source-name: test0
        # 数据库分片策略
        default-database-strategy:
          inline:
            sharding-column: order_id
            algorithm-expression: test$->{order_id % 2}
        # 默认的分表策略
        #default-table-strategy:

        tables:
          t_order:
            actual-data-nodes: test$->{0..1}.t_order_$->{0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_$->{order_id % 2}

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.iflytek.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
